In [1]:
import torch

In [2]:
torch.empty(3) # non-init tensor

tensor([0., 0., 0.])

In [3]:
torch.zeros(2,2) # create zero tensor

tensor([[0., 0.],
        [0., 0.]])

In [4]:
torch.tensor([2.5,0.1]) # create tensor

tensor([2.5000, 0.1000])

In [5]:
torch.rand(2,2) # create random value tensor

tensor([[0.3411, 0.1090],
        [0.5127, 0.3655]])

In [6]:
x = torch.ones(2,2, dtype=torch.float16) # create num one tensor
x.size()

torch.Size([2, 2])

In [7]:

y = torch.rand(2,2)
print(x)
print(y)
print("=================================")
print(x+y)
print(x-y)
print(x*y)
print(x/y)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)
tensor([[0.2862, 0.6997],
        [0.6179, 0.7953]])
tensor([[1.2862, 1.6997],
        [1.6179, 1.7953]])
tensor([[0.7138, 0.3003],
        [0.3821, 0.2047]])
tensor([[0.2862, 0.6997],
        [0.6179, 0.7953]])
tensor([[3.4939, 1.4292],
        [1.6185, 1.2574]])


In [8]:
x = torch.rand(5,3)

print(x[1,1])
print(x[1,1].item())# only can use when have only one tensor

tensor(0.1028)
0.10277712345123291


In [9]:
x = torch.rand(5,10)
print(x.view(50))# multple-D to one-D
print(x.view(-1, 25))# multple-D to two-D

tensor([0.9569, 0.9618, 0.6503, 0.0633, 0.7876, 0.1867, 0.6754, 0.3467, 0.2051,
        0.0633, 0.7381, 0.9330, 0.1304, 0.0338, 0.2398, 0.5017, 0.8700, 0.7186,
        0.4936, 0.6330, 0.4271, 0.9177, 0.7703, 0.2213, 0.5649, 0.6019, 0.6395,
        0.7330, 0.5124, 0.0137, 0.4880, 0.3221, 0.4267, 0.7753, 0.3208, 0.0543,
        0.4328, 0.4075, 0.7060, 0.7462, 0.0763, 0.7790, 0.8319, 0.1943, 0.4211,
        0.8268, 0.1112, 0.1933, 0.4584, 0.5629])
tensor([[0.9569, 0.9618, 0.6503, 0.0633, 0.7876, 0.1867, 0.6754, 0.3467, 0.2051,
         0.0633, 0.7381, 0.9330, 0.1304, 0.0338, 0.2398, 0.5017, 0.8700, 0.7186,
         0.4936, 0.6330, 0.4271, 0.9177, 0.7703, 0.2213, 0.5649],
        [0.6019, 0.6395, 0.7330, 0.5124, 0.0137, 0.4880, 0.3221, 0.4267, 0.7753,
         0.3208, 0.0543, 0.4328, 0.4075, 0.7060, 0.7462, 0.0763, 0.7790, 0.8319,
         0.1943, 0.4211, 0.8268, 0.1112, 0.1933, 0.4584, 0.5629]])


In [10]:
import numpy as np

In [11]:
a = torch.ones(5)
b = a.numpy()
print(type(b))

a.add_(1)
print(a)
print(b)# Call by refrence

<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [12]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)# use GPU
    y = torch.ones(5)
    y = y.to(device)# use GPU
    z = x + y 
#     z.numpy() #dis will error, cause numpy only handle cpu tensor
    z = z.to("cpu")
    z.numpy()

In [13]:
torch.ones(5, requires_grad=True)

tensor([1., 1., 1., 1., 1.], requires_grad=True)