In [1]:
import torch

In [2]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([ 1.0880,  1.2758, -0.2211], requires_grad=True)


In [3]:
y = x+2
print(y)

tensor([3.0880, 3.2758, 1.7789], grad_fn=<AddBackward0>)


In [4]:
z = y*y*2
z = z.mean()
print(z)

tensor(15.6207, grad_fn=<MeanBackward0>)


In [5]:
z.backward() #dz/dx
print(x.grad)

tensor([4.1173, 4.3678, 2.3718])


In [6]:
x = torch.randn(3, requires_grad=True)# cancel require grad_fn 1
x.requires_grad_(False)
print(x)

tensor([ 1.0880,  1.2758, -0.2211])


In [7]:
x = torch.randn(3, requires_grad=True)# cancel require grad_fn 2
y = x.detach()
print(y)

tensor([2.0453, 0.6106, 0.8212])


In [8]:
x = torch.randn(3, requires_grad=True)# cancel require grad_fn 2
with torch.no_grad():
    y = x+2
    print(y)

tensor([1.0957, 0.8396, 2.2228])


In [17]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()# will change weights tensor, cause weights set requires grad
    model_output.backward()
    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [19]:
weights.grad.zero_()
print(weights.grad)

tensor([0., 0., 0., 0.])
